### ISSUE TITLE
BNC Connection to Nitrate ISE sensor

### ISSUE THREAD

**Issue by hpollek** [VernierSoftwareTechnology/arduino#5]
Hello,
I am trying to use this sketch to run a TruLine Nitrate ISE Sensor, should I just be connecting the Sensor to a female BNC connector with the core connector going to A0 and the outer connector going to GND?

**Comment by dvernier** [comment]
Hello,

I do not know anything about a TruLine Nitrate Sensor. I have no idea what
signal it puts out.

Arduinos read voltages and that is what many of our sketches do.  You then
need to convert the voltage reading to a meaningful nitrate reading.

Dave Vernier

David L. Vernier
Founder and Co-President
Vernier Software & Technology
13979 SW Millikan Way
Beaverton, OR  97005
503-277-2299
1-888-Vernier (1-888-837-6437)
dvernier@vernier.com
www.vernier.com
