### ISSUE TITLE
Dissolved Oxygen Calibration arduino

### ISSUE THREAD

**Issue by kakaducsy** [VernierSoftwareTechnology/arduino#6]
Hi all,
I have just bought sensor DO
http://www.vernier.com/products/sensors/dissolved-oxygen-probes/odo-bta/
Can you help me calibration using arduino ?
I read analog signal of sensor DO but I dont have recipe convert analog signal to mg/l

**Comment by dvernier** [comment]
Hello,

There are several ways to do the calibration. First, you should look over the information at www.vernier.com/arduino

Specifically, one way is to use the manual method described at: 
https://www.vernier.com/engineering/arduino/analog-sensors/linear/

Another way, is to just use the sketch:
VernierAnalogAutoID or VernierAnalogAutoIDDisplay, which is in the dowload at the web site I first mentioned.

Finally, I am very close to posting  a library to do all this calibration stuff. Send me a note in a  week or so and I will send you the library files.

Dave Vernier
dvernier@vernier.com

**Comment by kakaducsy** [comment]
thanks
