### ISSUE TITLE
Nitrite Ion 

### ISSUE THREAD

**Issue by kakaducsy** [VernierSoftwareTechnology/arduino#7]
Hi All,
I am searching Nitrite Ion Sensor (NO2) of Vernier but Im not found.
If I want read NO2 then What sensor should I use?
Example If I using Ammonium Ion (NH4) http://www.vernier.com/products/sensors/ion-selective-electrodes/nh4-bta/
then How to calculate value NO2 ?

**Comment by dvernier** [comment]
If you want to use one of our Ion Selective Electrodes, of course, the easiest way is to use one of our interfaces (see:  http://www.vernier.com/products/interfaces/)

If you want to use one of our Ion Selective Electrodes with Arduino. You can read the raw voltage signal coming from the sensor, but you will have to deal with the calibration. In the sample sketches VernierAnalogAutoID and VernierAnalogAutoIDDisplay, we take one step in that direction:  We display the mV reading at the electrode.
